services:
  # PostgreSQL Database
  postgres:
    image: postgres:16-alpine
    container_name: jazz-postgres
    environment:
      POSTGRES_DB: jazz-flix
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - jazz-network


  # Kafka & Zookeeper
  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.1
    container_name: jazzflix-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - jazz-network

  kafka:
    image: confluentinc/cp-kafka:7.6.1
    container_name: jazzflix-kafka
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    networks:
      - jazz-network

  # MinIO
  minio:
    image: minio/minio:latest
    container_name: jazzflix-minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
    command: server /data --console-address ":9001"
    ports:
      - "9080:9000"
      - "9081:9001"
    volumes:
      - minio_data:/data
    networks:
      - jazz-network


volumes:
  postgres_data:
  minio_data:

networks:
  jazz-network:
    driver: bridge
